name: Desplegar Escritorio Virtual Con Audio

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Descargar archivos del repositorio
        uses: actions/checkout@v4

      - name: Configurar Entorno Web de Servidores
        uses: actions/configure-pages@v5 # Actualizado a v5 para soporte nativo de Node 24

      - name: Empaquetar el Escritorio
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Lanzar la web a Producción
        id: deployment
        uses: actions/deploy-pages@v4
